// Peg Solitaire.
// Positions are generated by legal reverse jumps from a one-peg solved state,
// so reversing the recorded move list always solves the generated board.

const PEG_SIZE = 7;
let pegBoard = [];
let pegSelected = null;
let pegSolutionMoves = [];

function pegDifficulty() {
    return ['easy','medium','hard','expert'].includes(window.PP_DIFFICULTY)
        ? window.PP_DIFFICULTY
        : 'medium';
}

function pegValid(row,col) {
    return (
        row >= 0 && row < PEG_SIZE &&
        col >= 0 && col < PEG_SIZE &&
        (row >= 2 && row <= 4 || col >= 2 && col <= 4)
    );
}

function pegIndex(row,col) {
    return row * PEG_SIZE + col;
}

function pegCoords(index) {
    return [Math.floor(index / PEG_SIZE),index % PEG_SIZE];
}

function reversePegOptions(board) {
    const options = [];

    for (let row = 0; row < PEG_SIZE; row++) {
        for (let col = 0; col < PEG_SIZE; col++) {
            if (!pegValid(row,col)) continue;
            const destination = pegIndex(row,col);
            if (board[destination] !== true) continue;

            for (const [dr,dc] of [[-1,0],[1,0],[0,-1],[0,1]]) {
                const middleRow = row - dr;
                const middleCol = col - dc;
                const sourceRow = row - 2 * dr;
                const sourceCol = col - 2 * dc;

                if (
                    !pegValid(middleRow,middleCol) ||
                    !pegValid(sourceRow,sourceCol)
                ) continue;

                const middle = pegIndex(middleRow,middleCol);
                const source = pegIndex(sourceRow,sourceCol);

                if (board[middle] === false && board[source] === false) {
                    options.push({ source,middle,destination });
                }
            }
        }
    }

    return options;
}

function generatePegs() {
    const targets = { easy:8, medium:14, hard:22, expert:30 };
    const target = targets[pegDifficulty()];
    let best = null;

    for (let attempt = 0; attempt < 160; attempt++) {
        const board = new Array(PEG_SIZE * PEG_SIZE).fill(null);
        for (let row = 0; row < PEG_SIZE; row++) {
            for (let col = 0; col < PEG_SIZE; col++) {
                if (pegValid(row,col)) board[pegIndex(row,col)] = false;
            }
        }
        board[pegIndex(3,3)] = true;

        const solution = [];

        while (solution.length < target) {
            const options = reversePegOptions(board);
            if (!options.length) break;
            const move = options[Math.floor(Math.random() * options.length)];

            board[move.destination] = false;
            board[move.middle] = true;
            board[move.source] = true;
            solution.unshift({ from:move.source,to:move.destination });
        }

        if (!best || solution.length > best.solution.length) {
            best = { board:[...board], solution:solution.map(move => ({...move})) };
        }
        if (solution.length >= target) break;
    }

    pegBoard = best.board;
    pegSolutionMoves = best.solution;
    pegSelected = null;
}

function initPegs() {
    const board = document.getElementById('arrow-board');
    board.style.gridTemplateColumns = 'repeat(' + PEG_SIZE + ',1fr)';
    board.innerHTML = '';
    generatePegs();

    for (let row = 0; row < PEG_SIZE; row++) {
        for (let col = 0; col < PEG_SIZE; col++) {
            const index = pegIndex(row,col);
            const cell = document.createElement('div');
            cell.className = 'grid-cell';
            cell.id = 'pegs-' + row + '-' + col;

            if (pegBoard[index] === null) {
                cell.classList.add('fixed');
                cell.style.opacity = '.18';
                cell.setAttribute('aria-hidden','true');
            } else {
                cell.setAttribute('role','button');
                cell.setAttribute('tabindex','0');
                cell.onclick = () => selectPeg(index);
                cell.onkeydown = event => {
                    if (event.key === 'Enter' || event.key === ' ') {
                        event.preventDefault();
                        selectPeg(index);
                    }
                };
            }

            board.appendChild(cell);
        }
    }

    renderPegs();
    checkPegsWin();
}

function legalPegMove(from,to) {
    if (pegBoard[from] !== true || pegBoard[to] !== false) return null;
    const [fromRow,fromCol] = pegCoords(from);
    const [toRow,toCol] = pegCoords(to);
    const dr = toRow - fromRow;
    const dc = toCol - fromCol;

    if (
        !((Math.abs(dr) === 2 && dc === 0) ||
          (Math.abs(dc) === 2 && dr === 0))
    ) return null;

    const middleRow = fromRow + dr / 2;
    const middleCol = fromCol + dc / 2;
    if (!pegValid(middleRow,middleCol)) return null;
    const middle = pegIndex(middleRow,middleCol);

    return pegBoard[middle] === true ? middle : null;
}

function selectPeg(index) {
    if (pegBoard[index] === null) return;

    if (pegSelected === null) {
        if (pegBoard[index] !== true) return;
        pegSelected = index;
        renderPegs();
        return;
    }

    if (index === pegSelected) {
        pegSelected = null;
        renderPegs();
        return;
    }

    if (pegBoard[index] === true) {
        pegSelected = index;
        renderPegs();
        return;
    }

    const middle = legalPegMove(pegSelected,index);
    if (middle === null) {
        const status = document.getElementById('arrow-status');
        status.innerText = 'A peg must jump over one adjacent peg into an empty hole two spaces away.';
        status.style.color = 'var(--accent-warning)';
        pegSelected = null;
        renderPegs();
        return;
    }

    const from = pegSelected;
    pegBoard[from] = false;
    pegBoard[middle] = false;
    pegBoard[index] = true;
    pegSelected = null;

    const expected = pegSolutionMoves[0];
    if (expected && expected.from === from && expected.to === index) pegSolutionMoves.shift();
    else pegSolutionMoves = [];

    renderPegs();
    checkPegsWin();
}

function pegLegalMoves() {
    const moves = [];

    for (let from = 0; from < pegBoard.length; from++) {
        if (pegBoard[from] !== true) continue;
        const [row,col] = pegCoords(from);

        for (const [dr,dc] of [[-1,0],[1,0],[0,-1],[0,1]]) {
            const toRow = row + dr * 2;
            const toCol = col + dc * 2;
            if (!pegValid(toRow,toCol)) continue;
            const to = pegIndex(toRow,toCol);
            if (legalPegMove(from,to) !== null) moves.push({from,to});
        }
    }

    return moves;
}

function renderPegs() {
    for (let row = 0; row < PEG_SIZE; row++) {
        for (let col = 0; col < PEG_SIZE; col++) {
            const index = pegIndex(row,col);
            const cell = document.getElementById('pegs-' + row + '-' + col);
            if (pegBoard[index] === null) continue;

            const hasPeg = pegBoard[index] === true;
            cell.innerText = hasPeg ? '●' : '○';
            cell.style.color = hasPeg ? 'var(--primary)' : 'var(--muted)';
            cell.style.background = index === pegSelected
                ? 'rgba(67,232,166,.22)'
                : 'rgba(8,10,24,.35)';
            cell.classList.toggle('empty',!hasPeg);
            cell.classList.toggle('selected',index === pegSelected);
            cell.setAttribute(
                'aria-label',
                (hasPeg ? 'Peg' : 'Empty hole') +
                ', row ' + (row + 1) + ', column ' + (col + 1)
            );
        }
    }
}

function pegsSolved() {
    return pegBoard.filter(value => value === true).length === 1;
}

function checkPegsWin() {
    const status = document.getElementById('arrow-status');
    const count = pegBoard.filter(value => value === true).length;

    if (pegsSolved()) {
        status.innerText = 'One peg remains. Puzzle solved!';
        status.style.color = 'var(--accent-success)';
    } else if (!pegLegalMoves().length) {
        status.innerText = count + ' pegs remain, but no legal jumps are available.';
        status.style.color = 'var(--accent-warning)';
    } else {
        status.innerText =
            pegDifficulty()[0].toUpperCase() + pegDifficulty().slice(1) +
            ' · ' + count + ' pegs remain. Jump over adjacent pegs into empty holes.';
        status.style.color = '';
    }
}

function pegsHint() {
    const known = pegSolutionMoves[0];
    const move = known || pegLegalMoves()[0];
    if (!move) return 'No legal jump remains.';
    const [row,col] = pegCoords(move.from);
    return {
        message:'The highlighted peg has a legal jump that keeps a known solution available.',
        selector:'#pegs-' + row + '-' + col
    };
}

window.PPEngine?.register('pegs', {
    version:1,
    serialize:() => ({
        version:1,
        board:[...pegBoard],
        selected:pegSelected,
        solutionMoves:pegSolutionMoves.map(move => ({...move}))
    }),
    restore:snapshot => {
        if (!snapshot || snapshot.version !== 1 || !Array.isArray(snapshot.board) || snapshot.board.length !== 49) return false;
        pegBoard = [...snapshot.board];
        pegSelected = snapshot.selected ?? null;
        pegSolutionMoves = (snapshot.solutionMoves || []).map(move => ({...move}));
        renderPegs();
        checkPegsWin();
        return true;
    },
    validate:() => pegBoard.filter(value => value !== null).length === 33,
    isSolved:pegsSolved,
    getHint:pegsHint
});
